spring:
  data:
    mongodb:
      host: 192.168.153.81
      port: 27017
      database: leadnews-history
  kafka:
    bootstrap-servers: 192.168.153.81:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
elasticsearch:
  host: 192.168.153.81
  port: 9200